
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #  redis:
#    host: 192.168.47.128
#    port: 6379
#    database: 0
  datasource:
    url: jdbc:mysql://47.105.155.220:3306/mytest?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081
  servlet:
    context-path: /screen
mybatis:
  mapperLocations: classpath:mapper/*.xml	#mapper文件路径
  typeAliasesPackage: com.screen.module	#要配置别名的类包路径
  configuration:
    call-setters-on-nulls: true #表单提交null 不保存null
